FROM node:20
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=optional
COPY . .

# Installiere Vite global, damit der Build nie an devDeps hängt
RUN npm i -g vite
RUN vite build

RUN npm i -g serve
EXPOSE 8080
CMD ["serve", "-s", "dist", "-l", "8080"]
